logger:
  level: "info"

storage:
  type: "memory"
  path: ""

bot:
  token: "your token"
  args: ""
  max_polls: 1
  result_remind: "21:00"

steam:
  api_key: "your api key"
  users:
    - name: "user1"
      steam_id: "steam id 1"
      telegram_id: 1
      chat_id: 11
    - name: "user2"
      steam_id: "steam id 2"
      telegram_id: 2
      chat_id: 12
