logger:
  level: "info"

bot:
  token: "your token"
  args: ""
  max_polls: 1
  result_remind: "21:00"

steam:
  api_key: "your api key"
  users:
    - name: "user1"
      sid: "steam id 1"
      tid: 1
    - name: "user2"
      sid: "steam id 2"
      tid: 2
